"""Entropy-gated per-sample trust regions (EG-PTGP).

Implements ``docs/entropy_gated_regions.md``. A training sample is either
an *objective* (misclassified, or correct-but-uncertain) or a *constraint*
(correct **and** low-entropy, i.e. "memorized"). The gate is
information-theoretic and two-sided::

    s_i = c_i · sigmoid(−β (H_i − H_mem))          (stability weight)
    α_i = 1 − s_i                                  (objective weight)

Two channels fall out of the gate:

* **Objective channel** (:func:`make_gated_loss`): the α-weighted
  cross-entropy — an *entropy hinge* that stops pushing a sample once its
  entropy falls below ``H_mem``.
* **Constraint channel** (:func:`EntropyGatedRegion`): the proposed step
  ``step = candidate − x`` is projected onto the polyhedral no-decrease
  cone generated by the memorized samples' margin gradients ``v_i``::

      s* = argmin ½‖s − step‖²   s.t.  ⟨−v̄_c, s⟩ ≤ ε̄_c   ∀ regions c

  solved through the NNLS dual (Appendix B). Only samples *about to be
  damaged by the aggregate step* pay a non-zero multiplier λ_c (the
  "price of stability", §4.4). Constraints are organised by a **region
  policy** (§3.7): one region (A-GEM-style mean), one per class, one per
  (class, runner-up) decision boundary, gradient-space clusters, random
  partition (control), or one per sample (exact cone).

The region operates on flat parameter vectors (it raveles pytrees at the
boundary) so it composes with every QQN oracle and line search. All
control flow is branch-free (``jnp.where`` / ``lax.fori_loop``) so the
region is ``jit`` / ``vmap`` safe; the number of constraints is bounded by
``max_constraints`` to keep shapes static.
"""

from typing import Callable, NamedTuple, Optional

import jax
import jax.numpy as jnp
from jax.flatten_util import ravel_pytree

from qqn_jax.regions.types import Region

__all__ = [
    "POLICIES",
    "EntropyGatedRegion",
    "EntropyGatedState",
    "GateStats",
    "entropy_gate_report",
    "gate_statistics",
    "make_gated_loss",
]

POLICIES = ("mean", "class", "pair", "gradient", "sample", "random")
_TINY = 1e-12


# ---------------------------------------------------------------------------
# The certainty gate (§3.1)
# ---------------------------------------------------------------------------
class GateStats(NamedTuple):
    """Per-sample gate quantities (all shape ``(N,)``).

    Attributes:
        entropy: predictive entropy ``H_i`` in nats.
        correct: ``c_i = 1[m_i > 0]``.
        margin: logit margin ``m_i = z_y − max_{j≠y} z_j``.
        runner_up: index of the runner-up class ``r_i``.
        stability: ``s_i ∈ [0, 1]`` (constraint weight).
        objective_weight: ``α_i = 1 − s_i``.
    """

    entropy: jnp.ndarray
    correct: jnp.ndarray
    margin: jnp.ndarray
    runner_up: jnp.ndarray
    stability: jnp.ndarray
    objective_weight: jnp.ndarray


def _margin_from_logits(logits, label):
    """Logit margin and runner-up for a ``(..., K)`` logits array."""
    K = logits.shape[-1]
    is_true = jnp.arange(K) == jnp.asarray(label)[..., None]
    true_logit = jnp.sum(jnp.where(is_true, logits, 0.0), axis=-1)
    masked = jnp.where(is_true, -jnp.inf, logits)
    runner_up = jnp.argmax(masked, axis=-1)
    margin = true_logit - jnp.max(masked, axis=-1)
    return margin, runner_up


def gate_statistics(
    logits, labels, h_mem: float = 0.5, beta: float = 10.0, hard: bool = False
) -> GateStats:
    """Compute entropy, correctness, margin and the two-sided gate weights.

    Args:
        logits: ``(N, K)`` logits.
        labels: ``(N,)`` integer labels.
        h_mem: memorization entropy threshold ``H_mem`` (nats).
        beta: gate sharpness ``β = 1/τ``.
        hard: if ``True`` use the hard gate ``1[H_i ≤ H_mem]``.
    """
    labels = jnp.asarray(labels)
    logp = jax.nn.log_softmax(logits, axis=-1)
    p = jnp.exp(logp)
    entropy = -jnp.sum(p * logp, axis=-1)
    margin, runner_up = _margin_from_logits(logits, labels)
    correct = margin > 0.0
    if hard:
        gate = (entropy <= h_mem).astype(logits.dtype)
    else:
        gate = jax.nn.sigmoid(-beta * (entropy - h_mem))
    stability = correct.astype(logits.dtype) * gate
    return GateStats(
        entropy=entropy,
        correct=correct,
        margin=margin,
        runner_up=runner_up,
        stability=stability,
        objective_weight=1.0 - stability,
    )


# ---------------------------------------------------------------------------
# Objective channel (§3.2): the entropy hinge
# ---------------------------------------------------------------------------
def make_gated_loss(
    logits_fn: Callable,
    X,
    y,
    *,
    h_mem: float = 0.5,
    beta: float = 10.0,
    hard: bool = False,
    l2: float = 0.0,
    normalize: bool = True,
) -> Callable:
    """Build the α-weighted cross-entropy ``Σ α_i ℓ_i / Σ α_i``.

    ``α_i`` is treated as a constant (``stop_gradient``) so the objective
    direction is exactly ``d_obj = Σ α_i g_i / Σ α_i``. Memorized samples
    contribute zero objective gradient; the region (constraint channel)
    is what protects them.

    Args:
        logits_fn: ``(params, X) -> (N, K)`` logits.
        X, y: the (full-batch) training set.
        h_mem, beta, hard: gate parameters (see :func:`gate_statistics`).
        l2: optional ridge penalty ``0.5·l2·‖θ‖²`` on flat params.
        normalize: divide by ``Σ α_i`` (default) or by ``N``.
    """
    X = jnp.asarray(X)
    y = jnp.asarray(y)

    def loss(params):
        logits = logits_fn(params, X)
        stats = gate_statistics(logits, y, h_mem=h_mem, beta=beta, hard=hard)
        alpha = jax.lax.stop_gradient(stats.objective_weight)
        logp = jax.nn.log_softmax(logits, axis=-1)
        nll = -jnp.take_along_axis(logp, y[:, None], axis=-1)[:, 0]
        denom = jnp.maximum(jnp.sum(alpha), 1.0) if normalize else nll.shape[0]
        value = jnp.sum(alpha * nll) / denom
        if l2 > 0.0:
            flat, _ = ravel_pytree(params)
            value = value + 0.5 * l2 * jnp.sum(flat**2)
        return value

    return loss


# ---------------------------------------------------------------------------
# Constraint channel (§3.3–§3.7)
# ---------------------------------------------------------------------------
class EntropyGatedState(NamedTuple):
    """State + diagnostics of the entropy-gated region.

    Attributes:
        step_count: number of ``update`` calls so far (drives warmup and
            centroid refresh).
        centroids: ``(k, P)`` unit gradient-space centroids (``gradient``
            policy only; a ``(1, 1)`` placeholder otherwise).
        n_memorized: ``|M|`` at the last accepted iterate.
        n_objective: ``N − |M|``.
        mean_entropy: mean predictive entropy at the last iterate.
        train_accuracy: fraction correct at the last iterate.
    """

    step_count: jnp.ndarray
    centroids: jnp.ndarray
    n_memorized: jnp.ndarray
    n_objective: jnp.ndarray
    mean_entropy: jnp.ndarray
    train_accuracy: jnp.ndarray


def _hildreth_nnls(G, r, sweeps: int):
    """Solve ``min_{λ≥0} ½λᵀGλ − λᵀr`` by projected Gauss–Seidel.

    For ``k = 1`` this is exact after one sweep (the closed form of §3.4).
    Rows/columns of ``G`` belonging to invalid constraints must already be
    masked to the identity with ``r = 0`` so their multipliers stay zero.
    """
    k = G.shape[0]
    diag = jnp.diagonal(G)
    diag = jnp.where(diag > _TINY, diag, jnp.ones_like(diag))

    def coord(c, lam):
        resid = jnp.dot(G[c], lam) - r[c]
        new = jnp.maximum(0.0, lam[c] - resid / diag[c])
        return lam.at[c].set(new)

    def sweep(_, lam):
        return jax.lax.fori_loop(0, k, coord, lam)

    lam0 = jnp.zeros((k,), dtype=G.dtype)
    return jax.lax.fori_loop(0, sweeps, sweep, lam0)


def _project_cone(step, Vbar, eps_c, valid, sweeps: int):
    """Project ``step`` onto ``{s : ⟨−v̄_c, s⟩ ≤ ε̄_c ∀ valid c}``.

    Returns ``(s_proj, λ)``; ``s_proj = step + Σ_c λ_c v̄_c``.
    """
    k = Vbar.shape[0]
    A = jnp.where(valid[:, None], -Vbar, 0.0)
    G = A @ A.T + jnp.diag(jnp.where(valid, 0.0, 1.0).astype(A.dtype))
    b = A @ step
    r = jnp.where(valid, b - eps_c, 0.0)
    lam = _hildreth_nnls(G, r, sweeps)
    lam = jnp.where(valid, lam, 0.0)
    return step - A.T @ lam, lam


def _aggregate(assign, k: int, V, w, eps_i):
    """Weighted region means, slacks, validity mask and dispersion radii."""
    onehot = jax.nn.one_hot(assign, k, dtype=V.dtype) * w[:, None]  # (m, k)
    wsum = jnp.sum(onehot, axis=0)
    valid = wsum > _TINY
    safe = jnp.where(valid, wsum, 1.0)
    Vbar = (onehot.T @ V) / safe[:, None]
    eps_bar = (onehot.T @ eps_i) / safe
    dist = jnp.linalg.norm(V - Vbar[assign], axis=1)
    member = onehot > 0.0
    sigma = jnp.max(jnp.where(member, dist[:, None], 0.0), axis=0)
    return Vbar, eps_bar, valid, sigma


def _gradient_clusters(V, w, centroids, iters: int):
    """Weighted spherical k-means on margin gradients (Lloyd iterations).

    Clustering on *direction* rules out the cancellation failure mode of
    §4.5 by construction: opposed gradients cannot share a region.
    Returns ``(assignments, refreshed_centroids)``.
    """
    k = centroids.shape[0]
    Vn = V / (jnp.linalg.norm(V, axis=1, keepdims=True) + _TINY)

    def lloyd(_, C):
        assign = jnp.argmax(Vn @ C.T, axis=1)
        onehot = jax.nn.one_hot(assign, k, dtype=V.dtype) * w[:, None]
        newC = onehot.T @ Vn
        cnorm = jnp.linalg.norm(newC, axis=1, keepdims=True)
        return jnp.where(cnorm > _TINY, newC / jnp.maximum(cnorm, _TINY), C)

    C = jax.lax.fori_loop(0, iters, lloyd, centroids.astype(V.dtype))
    assign = jnp.argmax(Vn @ C.T, axis=1)
    return assign, C


def EntropyGatedRegion(
    logits_fn: Callable,
    X,
    y,
    *,
    h_mem: float = 0.5,
    tau: float = 0.1,
    hard_gate: bool = False,
    s_min: float = 0.05,
    policy: str = "pair",
    num_regions: int = 8,
    cluster_iters: int = 3,
    refresh_every: int = 10,
    kappa: float = 0.1,
    zeta: float = 0.0,
    max_constraints: Optional[int] = None,
    param_mask=None,
    dual_sweeps: int = 20,
    warmup_steps: int = 0,
    dead_zone_ratio: float = 0.0,
    dead_zone_relax: float = 0.1,
    seed: int = 0,
) -> Region:
    """Project the step onto the memorized samples' no-decrease cone.

    Args:
        logits_fn: ``(params, x_batch) -> (n, K)`` logits; must accept
            single-sample batches (used under ``vmap(grad)`` for margin
            gradients).
        X, y: the training set the gate and constraints are drawn from.
        h_mem: memorization entropy ``H_mem`` in nats (§3.1). Roughly
            ``0.2–0.7`` for 10-class problems; scale with ``log K``.
        tau: soft-gate band width; ``β = 1/τ``.
        hard_gate: use ``1[H ≤ H_mem]`` instead of the sigmoid gate.
        s_min: samples with ``s_i ≤ s_min`` are excluded from ``M``.
        policy: region policy (§3.7): ``"mean"`` (one A-GEM-style region),
            ``"class"``, ``"pair"`` ((class, runner-up) — one region per live
            decision boundary; the recommended default), ``"gradient"``
            (spherical k-means on ``v_i``), ``"sample"`` (exact cone), or
            ``"random"`` (the control partition).
        num_regions: ``k`` for the ``gradient`` / ``random`` policies.
        cluster_iters: Lloyd iterations per projection (``gradient``).
        refresh_every: centroid refresh period ``T_c`` in accepted steps.
        kappa: slack coefficient ``ε_i = κ (1 − s_i) ‖v_i‖``.
        zeta: dispersion tightening ``ε̄_c ← ε̄_c − ζ σ_c ‖step‖``
            (``ζ = 1`` makes the region constraint imply every member's).
        max_constraints: cap on ``|M|`` per step (top-``s`` samples); keeps
            the per-sample gradient cost static and bounded.
        param_mask: optional flat ``(P,)`` boolean mask restricting the
            constraints to a parameter subset (e.g. head-only, §3.6).
        dual_sweeps: Hildreth sweeps for the NNLS dual.
        warmup_steps: accepted steps of plain (unprojected) training before
            the gate is trusted (§3.8, line 5).
        dead_zone_ratio: if ``‖s*‖ < δ‖step‖`` re-solve with relaxed slack
            ``ε̄_c + relax·‖v̄_c‖‖step‖`` (§8 dead-zone guard). ``0`` disables.
        dead_zone_relax: the relaxation fraction above.
        seed: RNG seed for centroid init / random partition.
    """
    if policy not in POLICIES:
        raise ValueError(f"Unknown policy {policy!r}; choose from {POLICIES}.")
    X = jnp.asarray(X)
    y = jnp.asarray(y, dtype=jnp.int32)
    N = X.shape[0]
    m = N if max_constraints is None else min(int(max_constraints), N)
    beta = 1.0 / float(tau)
    key = jax.random.PRNGKey(seed)
    random_assign = jax.random.randint(key, (N,), 0, max(1, num_regions))
    mask = None if param_mask is None else jnp.asarray(param_mask)

    def margin_grads(flat_p, unravel, Xs, ys):
        def margin_one(fp, xi, yi):
            logit = logits_fn(unravel(fp), xi[None, ...])[0]
            margin, _ = _margin_from_logits(logit, yi)
            return margin

        V = jax.vmap(jax.grad(margin_one), in_axes=(None, 0, 0))(flat_p, Xs, ys)
        if mask is not None:
            V = V * mask.astype(V.dtype)[None, :]
        return V

    def select(stats):
        """Top-``m`` memorized samples and their constraint weights."""
        s = stats.stability
        w_all = jnp.where(s > s_min, s, 0.0)
        idx = jnp.arange(N) if m == N else jnp.argsort(-w_all)[:m]
        return idx, w_all[idx]

    def assign_regions(idx, stats, V, w, centroids, K: int):
        if policy == "mean":
            return jnp.zeros((m,), jnp.int32), 1
        if policy == "class":
            return y[idx], K
        if policy == "pair":
            return y[idx] * K + stats.runner_up[idx].astype(jnp.int32), K * K
        if policy == "sample":
            return jnp.arange(m, dtype=jnp.int32), m
        if policy == "random":
            return random_assign[idx], num_regions
        assign, _ = _gradient_clusters(V, w, centroids, cluster_iters)
        return assign, num_regions

    def init(params):
        flat, _ = ravel_pytree(params)
        if policy == "gradient":
            C = jax.random.normal(key, (num_regions, flat.shape[0]), flat.dtype)
            C = C / jnp.linalg.norm(C, axis=1, keepdims=True)
        else:
            C = jnp.zeros((1, 1), dtype=flat.dtype)
        zero = jnp.asarray(0.0, dtype=flat.dtype)
        return EntropyGatedState(
            step_count=jnp.asarray(0, jnp.int32),
            centroids=C,
            n_memorized=zero,
            n_objective=jnp.asarray(float(N), dtype=flat.dtype),
            mean_entropy=zero,
            train_accuracy=zero,
        )

    def project(params, candidate, state):
        flat_p, unravel = ravel_pytree(params)
        flat_c, _ = ravel_pytree(candidate)
        step = flat_c - flat_p
        step_norm = jnp.linalg.norm(step)

        logits = logits_fn(params, X)
        K = logits.shape[-1]
        stats = gate_statistics(logits, y, h_mem=h_mem, beta=beta, hard=hard_gate)
        idx, w = select(stats)

        V = margin_grads(flat_p, unravel, X[idx], y[idx])
        vnorm = jnp.linalg.norm(V, axis=1)
        eps_i = kappa * (1.0 - stats.stability[idx]) * vnorm

        assign, k = assign_regions(idx, stats, V, w, state.centroids, K)
        Vbar, eps_c, valid, sigma = _aggregate(assign, k, V, w, eps_i)
        eps_c = jnp.maximum(eps_c - zeta * sigma * step_norm, 0.0)

        s_proj, _lam = _project_cone(step, Vbar, eps_c, valid, dual_sweeps)
        if dead_zone_ratio > 0.0:
            ratio = jnp.linalg.norm(s_proj) / (step_norm + _TINY)
            relaxed = (
                eps_c + dead_zone_relax * jnp.linalg.norm(Vbar, axis=1) * step_norm
            )
            s_relax, _ = _project_cone(step, Vbar, relaxed, valid, dual_sweeps)
            s_proj = jnp.where(ratio < dead_zone_ratio, s_relax, s_proj)

        active = state.step_count >= warmup_steps
        s_out = jnp.where(active, s_proj, step)
        return unravel(flat_p + s_out)

    def update(state, info):
        new_params = info.new_params
        logits = logits_fn(new_params, X)
        stats = gate_statistics(logits, y, h_mem=h_mem, beta=beta, hard=hard_gate)
        dtype = stats.entropy.dtype
        n_mem = jnp.sum((stats.stability > s_min).astype(dtype))

        centroids = state.centroids
        if policy == "gradient":
            flat_p, unravel = ravel_pytree(new_params)
            idx, w = select(stats)
            V = margin_grads(flat_p, unravel, X[idx], y[idx])
            _, fresh = _gradient_clusters(V, w, centroids, cluster_iters)
            do_refresh = (state.step_count % max(1, refresh_every)) == 0
            centroids = jnp.where(do_refresh, fresh, centroids)

        return EntropyGatedState(
            step_count=state.step_count + 1,
            centroids=centroids,
            n_memorized=n_mem,
            n_objective=jnp.asarray(float(N), dtype) - n_mem,
            mean_entropy=jnp.mean(stats.entropy),
            train_accuracy=jnp.mean(stats.correct.astype(dtype)),
        )

    return Region(init=init, project=project, update=update)


# ---------------------------------------------------------------------------
# Diagnostics (§7.1)
# ---------------------------------------------------------------------------
def entropy_gate_report(
    logits_fn, X, y, params, *, h_mem=0.5, tau=0.1, hard=False, s_min=0.05
):
    """Return a dict of gate diagnostics at ``params`` (plain floats)."""
    logits = logits_fn(params, jnp.asarray(X))
    stats = gate_statistics(
        logits, jnp.asarray(y), h_mem=h_mem, beta=1.0 / tau, hard=hard
    )
    mem = stats.stability > s_min
    return {
        "n_memorized": int(jnp.sum(mem)),
        "n_objective": int(mem.shape[0] - jnp.sum(mem)),
        "accuracy": float(jnp.mean(stats.correct)),
        "mean_entropy": float(jnp.mean(stats.entropy)),
        "frac_below_h_mem": float(jnp.mean(stats.entropy <= h_mem)),
        "margin_p10": float(jnp.percentile(stats.margin, 10)),
        "margin_p50": float(jnp.percentile(stats.margin, 50)),
        "margin_p90": float(jnp.percentile(stats.margin, 90)),
    }
